global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'brvm-go-api'
    static_configs:
      - targets: ['go-api:8080']
    metrics_path: /metrics

  - job_name: 'brvm-rust-engine'
    static_configs:
      - targets: ['rust-engine:50051']

  - job_name: 'brvm-go-collector'
    static_configs:
      - targets: ['go-collector:9090']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
